spring:

  application:
    name: olpang

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:olpang
    username: sa
    password:
    driver-class-name: org.h2.Driver
