spring:

  application:
    name: olpang

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true  # 페이지 번호 0이 아닌 1부터 시작
        default-page-size: 5  # 기본 페이지 사이즈

  datasource:
    url: jdbc:h2:mem:olpang
    username: sa
    password:
    driver-class-name: org.h2.Driver
